version: "3.3"
services:
  1p-custom-agent:
    container_name: 1p-custom-agent
    restart: always
    image: elvenworks/1p-agent:$DOCKER_IMAGE_VERSION
    logging:
      driver: "json-file"
    environment:
      ENVIRONMENT_ID: $ENVIRONMENT_ID
    depends_on:
      - docker-collector-logs

  docker-collector-logs:
    container_name: docker-collector-logs
    restart: always
    image: logzio/docker-collector-logs
    environment:
      LOGZIO_TOKEN: $LOGZIO_TOKEN
      LOGZIO_URL: listener.logz.io:5015
      additionalFields: "agent-env-id=$ENVIRONMENT_ID"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /var/lib/docker/containers:/var/lib/docker/containers